name: 'Sendgrid Sync'
description: 'Syncronize Sendgrid Templates'
inputs:
  dry-run:
    required: false
    description: "Only show affected files"
    default: "false"
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  templates:
    description: "String of templates modified separated by a comma"