name: 'Sendgrid Sync'
description: 'Syncronize Sendgrid Templates'
inputs:
  dry-run:
    required: false
    description: "Only show affected files"
    default: "false"
  mode:
    required: true
    description: "The mode to run the action. Could be `sync` or `apply`"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --dry-run ${{ inputs.dry-run }}
    - --mode ${{ inputs.mode }}
